//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppForSEII2526.Maui.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppForSEII2526.Maui.Resources.Languages.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All Brands.
        /// </summary>
        internal static string AllBrands {
            get {
                return ResourceManager.GetString("AllBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All Days.
        /// </summary>
        internal static string AllDays {
            get {
                return ResourceManager.GetString("AllDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All Names.
        /// </summary>
        internal static string AllNames {
            get {
                return ResourceManager.GetString("AllNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All Types .
        /// </summary>
        internal static string AllTypes {
            get {
                return ResourceManager.GetString("AllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click &apos;Apply filters&apos; after selecting type and/or date..
        /// </summary>
        internal static string AssistantApplyFilters {
            get {
                return ResourceManager.GetString("AssistantApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click &apos;Clear filters&apos; to see all available classes again..
        /// </summary>
        internal static string AssistantClearFilters {
            get {
                return ResourceManager.GetString("AssistantClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the classes you want and click the &apos;Create Plan&apos; button..
        /// </summary>
        internal static string AssistantCreatePlan {
            get {
                return ResourceManager.GetString("AssistantCreatePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can filter by day to see only the classes on that date..
        /// </summary>
        internal static string AssistantFilterDay {
            get {
                return ResourceManager.GetString("AssistantFilterDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can filter by class type, like Yoga or Strength..
        /// </summary>
        internal static string AssistantFilterType {
            get {
                return ResourceManager.GetString("AssistantFilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello! How can I help you today?.
        /// </summary>
        internal static string AssistantGreeting {
            get {
                return ResourceManager.GetString("AssistantGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I can help you select classes, apply filters, and create your plan..
        /// </summary>
        internal static string AssistantHelp {
            get {
                return ResourceManager.GetString("AssistantHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I can show you all the classes you can add to your plan this week..
        /// </summary>
        internal static string AssistantListClasses {
            get {
                return ResourceManager.GetString("AssistantListClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type your message....
        /// </summary>
        internal static string AssistantPlaceholder {
            get {
                return ResourceManager.GetString("AssistantPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uncheck the class in the list and your selection and total price will update..
        /// </summary>
        internal static string AssistantRemoveClass {
            get {
                return ResourceManager.GetString("AssistantRemoveClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        internal static string AssistantSend {
            get {
                return ResourceManager.GetString("AssistantSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In the app&apos;s shop you can buy products or accessories..
        /// </summary>
        internal static string AssistantShop {
            get {
                return ResourceManager.GetString("AssistantShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The total price updates automatically according to the classes you select..
        /// </summary>
        internal static string AssistantTotalPrice {
            get {
                return ResourceManager.GetString("AssistantTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, I didn’t understand that. Can you rephrase it?.
        /// </summary>
        internal static string AssistantUnknown {
            get {
                return ResourceManager.GetString("AssistantUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browse Items.
        /// </summary>
        internal static string BrowseItems {
            get {
                return ResourceManager.GetString("BrowseItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string ClassName {
            get {
                return ResourceManager.GetString("ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Plan.
        /// </summary>
        internal static string CreatePlan {
            get {
                return ResourceManager.GetString("CreatePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dark.
        /// </summary>
        internal static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deuteranopia (Green-blind).
        /// </summary>
        internal static string DeuteranopiaTheme {
            get {
                return ResourceManager.GetString("DeuteranopiaTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter by Brand.
        /// </summary>
        internal static string FilterByBrand {
            get {
                return ResourceManager.GetString("FilterByBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter by Day.
        /// </summary>
        internal static string FilterByDay {
            get {
                return ResourceManager.GetString("FilterByDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter by Name.
        /// </summary>
        internal static string FilterByName {
            get {
                return ResourceManager.GetString("FilterByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter by Type.
        /// </summary>
        internal static string FilterByType {
            get {
                return ResourceManager.GetString("FilterByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Font Size.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjust the text size for better readability.
        /// </summary>
        internal static string FontSizeDescription {
            get {
                return ResourceManager.GetString("FontSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hide Filters.
        /// </summary>
        internal static string HideFilters {
            get {
                return ResourceManager.GetString("HideFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose your preferred language.
        /// </summary>
        internal static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Large.
        /// </summary>
        internal static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Light.
        /// </summary>
        internal static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Protanopia (Red-blind).
        /// </summary>
        internal static string ProtanopiaTheme {
            get {
                return ResourceManager.GetString("ProtanopiaTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Report Incident.
        /// </summary>
        internal static string ReportIncident {
            get {
                return ResourceManager.GetString("ReportIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Classes.
        /// </summary>
        internal static string SelectClasses {
            get {
                return ResourceManager.GetString("SelectClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the classes you want to enroll in for next week.
        /// </summary>
        internal static string SelectClassesDescription {
            get {
                return ResourceManager.GetString("SelectClassesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the items you want to purchase.
        /// </summary>
        internal static string SelectItemsDescription {
            get {
                return ResourceManager.GetString("SelectItemsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shop.
        /// </summary>
        internal static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Filters.
        /// </summary>
        internal static string ShowFilters {
            get {
                return ResourceManager.GetString("ShowFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Small.
        /// </summary>
        internal static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose your preferred theme.
        /// </summary>
        internal static string ThemeDescription {
            get {
                return ResourceManager.GetString("ThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tritanopia (Blue-blind).
        /// </summary>
        internal static string TritanopiaTheme {
            get {
                return ResourceManager.GetString("TritanopiaTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your Complete Gym Management System.
        /// </summary>
        internal static string YourCompleteGymManagementSystem {
            get {
                return ResourceManager.GetString("YourCompleteGymManagementSystem", resourceCulture);
            }
        }
    }
}
